---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Install git from source
  ansible.builtin.include_role:
    name: andrewrothstein.git_build
  when: git_installer == 'source'

- name: Running {{ git_installer }} installer...
  ansible.builtin.include_tasks: '{{ git_installer }}.yml'
  when: git_installer != 'source'

- name: Configurating git in {{ git_target_cfg }}
  become: '{{ git_privilege_escalation }}'
  become_user: root
  with_items: '{{ git_config_protocol_map | default([]) }}'
  ansible.builtin.blockinfile:
    create: true
    dest: '{{ git_target_cfg }}'
    mode: '644'
    state: '{{ "present" if item.enabled | default(true) else "absent" }}'
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.uid }}"
    block: |
      [url "{{ item.url }}"]
        insteadOf = {{ item.insteadOf }}
