---
- name: Install git os pkgs...
  become: '{{ git_privilege_escalation }}'
  become_user: root
  ansible.builtin.package:
    name: '{{ git_os_pkgs }}'
    state: present

- name: Install git-lfs os pkgs...
  when: git_lfs_enable
  become: '{{ git_privilege_escalation }}'
  become_user: root
  ansible.builtin.package:
    name: '{{ git_lfs_os_pkgs }}'
    state: present
